language: java
jdk:
  - oraclejdk8
env:
  - SCRIPT=bin/unit-tests.sh
  - SCRIPT=bin/journey-test.sh

deploy:
  provider: heroku
  api_key: b4aa8904-97a5-4e8d-b834-4e5ff1109593
  app: radiant-tor-73335
